-- Sample data insertion (matches frontend mock data)
-- Run this after the main schema.sql

-- Insert sample projects (matching tasklistData.js)
INSERT INTO projects (
    project_name,
    employee_id,
    position,
    department,
    five_s_group_name,
    project_area,
    project_start_date,
    project_end_date,
    problems_encountered,
    solution_approach,
    results_achieved,
    five_s_type,
    improvement_topic,
    sgs_smart,
    sgs_strong,
    sgs_green,
    before_project_image,
    after_project_image,
    created_date_th,
    submitted_date_th,
    status,
    form_type,
    created_date,
    submitted_date
) VALUES 
(
    'ปรับปรุงกระบวนการจัดเก็บสินค้า Thailand 5.0',
    '241303',
    'เจ้าหน้าที่',
    'IT&DM',
    '5ส ณ บางปูใหม่',
    'คลังสินค้าบางปู',
    '2025-06-01',
    '2025-06-15',
    'พบปัญหาการจัดเก็บสินค้าไม่เป็นระบบ สินค้าหาไม่เจอ และใช้เวลานานในการค้นหา ทำให้ประสิทธิภาพการทำงานลดลง',
    'ใช้หลัก 5ส ในการจัดระเบียบพื้นที่ จัดทำป้ายกำกับสินค้า และสร้างแผนผังตำแหน่งการจัดเก็บ',
    'ลดเวลาในการค้นหาสินค้าได้ 50% เพิ่มประสิทธิภาพการทำงาน และสร้างพื้นที่ทำงานที่สะอาดเป็นระเบียบ',
    'ส1',
    'Cost',
    'People',
    'Workplace',
    'Teamwork',
    'warehouse_before_messy_storage.jpg',
    'warehouse_after_organized_5s.jpg',
    '19/06/2025',
    '19/06/2025',
    'APPROVED',
    'genba',
    '2025-06-19 10:30:00+07',
    '2025-06-19 10:30:00+07'
),
(
    'ปรับปรุงระบบการจัดการข้อมูลดิจิทัลแบบครบวงจร',
    '251307',
    'นักวิเคราะห์',
    'IT&DM',
    '5ส ณ บางปูใหม่',
    'ศูนย์ข้อมูลกลาง IT-DC1',
    '2025-06-10',
    '2025-06-18',
    'ระบบจัดการข้อมูลล้าสมัย การสำรองข้อมูลไม่เป็นระบบ และการเข้าถึงข้อมูลใช้เวลานาน ส่งผลต่อประสิทธิภาพการทำงาน',
    'นำเทคโนโลยี Cloud Computing มาใช้ ปรับปรุงระบบฐานข้อมูล และจัดทำระบบสำรองข้อมูลอัตโนมัติ',
    'เพิ่มความเร็วในการเข้าถึงข้อมูล 70% ลดเวลาในการสำรองข้อมูล 90% และเพิ่มความปลอดภัยของข้อมูล',
    'ส5',
    'Quality',
    'Factory',
    'Energy_3R',
    'Branding',
    'datacenter_before_old_system.jpg',
    'datacenter_after_cloud_upgrade.jpg',
    '18/06/2025',
    '18/06/2025',
    'APPROVED',
    'best_kaizen',
    '2025-06-18 14:15:00+07',
    '2025-06-18 14:15:00+07'
),
(
    'พัฒนาระบบการทำงานแบบอัตโนมัติในไลน์ผลิต',
    '261401',
    'หัวหน้าแผนก',
    'PD',
    '5ส ณ โรงงาน A',
    'ไลน์ผลิตอัตโนมัติ A1',
    '2025-06-10',
    '2025-06-17',
    'กระบวนการผลิตยังต้องใช้คนงานจำนวนมาก ทำให้เกิดความผิดพลาดจากมนุษย์ และความเร็วในการผลิตไม่สม่ำเสมอ',
    'นำเทคโนโลยีระบบอัตโนมัติมาใช้ในไลน์ผลิต ติดตั้งเซนเซอร์ตรวจจับ และระบบควบคุมอัตโนมัติ',
    'เพิ่มความเร็วในการผลิต 30% ลดข้อผิดพลาดจากมนุษย์ 80% และประหยัดต้นทุนแรงงาน',
    'ส4',
    'Quality',
    'Factory',
    'Energy_3R',
    'Branding',
    'production_line_before_manual_process.jpg',
    NULL,
    '17/06/2025',
    '17/06/2025',
    'EDIT',
    'suggestion',
    '2025-06-17 09:00:00+07',
    '2025-06-17 09:00:00+07'
),
(
    'ปรับปรุงกระบวนการผลิตชิ้นส่วนยานยนต์',
    '241303',
    'เจ้าหน้าที่',
    'PC',
    '5ส ณ โรงงาน B',
    'โรงงานผลิตชิ้นส่วน B2',
    '2025-06-05',
    '2025-06-14',
    'กระบวนการผลิตมีการสูญเสียวัสดุสูง พื้นที่ทำงานไม่เป็นระเบียบ และเครื่องจักรจัดวางไม่เหมาะสม',
    'จัดระเบียบพื้นที่ทำงานตามหลัก 5ส ปรับปรุงการไหลของวัสดุ และจัดวางเครื่องจักรใหม่',
    'ลดการสูญเสียวัสดุ 25% เพิ่มประสิทธิภาพการผลิต 20% และสร้างสภาพแวดล้อมการทำงานที่ดีขึ้น',
    'ส2',
    'Cost',
    'People',
    'Energy_3R',
    'Teamwork',
    'factory_floor_before_cluttered_layout.jpg',
    'factory_floor_after_lean_layout.jpg',
    '16/06/2025',
    '16/06/2025',
    'WAITING',
    'genba',
    '2025-06-16 11:45:00+07',
    '2025-06-16 11:45:00+07'
),
(
    'ลดของเสียในการผลิตผลิตภัณฑ์พลาสติก',
    '251307',
    'นักวิเคราะห์',
    'QA',
    '5ส ณ คลังสินค้า',
    'ไลน์ผลิตพลาสติก QA-01',
    '2025-06-08',
    '2025-06-15',
    'อัตราของเสียในการผลิตสูงถึง 15% เนื่องจากการตั้งค่าพารามิเตอร์เครื่องจักรไม่เหมาะสม และการควบคุมคุณภาพไม่สม่ำเสมอ',
    'ปรับปรุงพารามิเตอร์การผลิต จัดทำมาตรฐานการตรวจสอบคุณภาพ และฝึกอบรมพนักงานเรื่องการควบคุมคุณภาพ',
    'ลดอัตราของเสียจาก 15% เหลือ 5% ประหยัดต้นทุนวัสดุได้ 200,000 บาท/เดือน และเพิ่มคุณภาผลิตภัณฑ์',
    'ส4',
    'Quality',
    'People',
    'Energy_3R',
    'Branding',
    'plastic_production_before_high_defects.jpg',
    NULL,
    '15/06/2025',
    '15/06/2025',
    'APPROVED',
    'suggestion',
    '2025-06-15 16:20:00+07',
    '2025-06-15 16:20:00+07'
),
(
    'เพิ่มประสิทธิภาพการจัดเก็บและควบคุมสต็อก',
    '261401',
    'หัวหน้าแผนก',
    'PD',
    '5ส ณ โรงงาน A',
    'คลังวั�ถุดิบโรงงาน A',
    '2025-06-07',
    '2025-06-14',
    'การจัดเก็บวัตถุดิบไม่เป็นระบบ ขาดการควบคุมสต็อกที่แม่นยำ และเกิดการสูญหายของวัตถุดิบบ่อยครั้ง',
    'จัดทำระบบ FIFO สำหรับวัตถุดิบ ติดตั้งระบบ Barcode และปรับปรุงการจัดวางพื้นที่เก็บของ',
    'ลดการสูญหายของวัตถุดิบ 95% เพิ่มความแม่นยำในการควบคุมสต็อก และลดเวลาในการค้นหาวัตถุดิบ 60%',
    'ส3',
    'Cost',
    'Factory',
    'Energy_3R',
    'Teamwork',
    'material_storage_before_disorganized.jpg',
    'material_storage_after_fifo_system.jpg',
    '14/06/2025',
    '14/06/2025',
    'WAITING',
    'best_kaizen',
    '2025-06-14 13:10:00+07',
    '2025-06-14 13:10:00+07'
),
(
    'ปรับปรุงระบบความปลอดภัยในการทำงาน',
    '241303',
    'เจ้าหน้าที่',
    'HR&AD',
    '5ส ณ บางปูใหม่',
    'อาคารสำนักงานบางปู',
    '2025-06-05',
    '2025-06-13',
    'พบจุดเสี่ยงด้านความปลอดภัยหลายจุดในสำนักงาน ขาดการฝึกอบรมความปลอดภัย และอุปกรณ์ป้องกันไม่เพียงพอ',
    'จัดทำแผนความปลอดภัยใหม่ ติดตั้งอุปกรณ์ป้องกันเพิ่มเติม และจัดอบรมความปลอดภัยแก่พนักงานทุกคน',
    'ลดอุบัติเหตุในการทำงาน 100% เพิ่มความตรวจะขื่อของพนักงานต่อความปลอดภัย และได้รับประกาศนียบัตรความปลอดภัย',
    'ส5',
    'Safety',
    'People',
    'Workplace',
    'Teamwork',
    'office_safety_before_hazards.jpg',
    'office_safety_after_improvements.jpg',
    '13/06/2025',
    '13/06/2025',
    'EDIT',
    'best_kaizen',
    '2025-06-13 08:30:00+07',
    '2025-06-13 08:30:00+07'
),
(
    'การจัดการพลังงานและลดการใช้ไฟฟ้า',
    '251307',
    'นักวิเคราะห์',
    'IT&DM',
    '5ส ณ บางปูใหม่',
    'อาคารสำนักงานและศูนย์ข้อมูล',
    '2025-06-01',
    '2025-06-12',
    'การใช้พลังงานไฟฟ้าสูงเกินความจำเป็น อุปกรณ์ IT เปิดทิ้งไว้ตลอดเวลา และระบบแอร์ทำงานไม่มีประสิทธิภาพ',
    'ติดตั้งระบบควบคุมพลังงานอัตโนมัติ จัดทำ Energy Management Policy และฝึกอบรมพนักงานเรื่องการประหยัดพลังงาน',
    'ลดการใช้ไฟฟ้า 35% ประหยัดค่าไฟฟ้า 150,000 บาท/เดือน และได้รับรางวัลองค์กรประหยัดพลังงานดีเด่น',
    'ส4',
    'Env',
    'Factory',
    'Energy_3R',
    'Branding',
    'energy_management_before_wasteful.jpg',
    'energy_management_after_efficient.jpg',
    '12/06/2025',
    '12/06/2025',
    'APPROVED',
    'best_kaizen',
    '2025-06-12 15:45:00+07',
    '2025-06-12 15:45:00+07'
);

-- Update the sequence to continue from where we left off
SELECT setval('projects_id_seq', (SELECT MAX(id) FROM projects));

-- Add some sample sessions
INSERT INTO sessions (
    employee_id,
    login_time,
    last_activity,
    ip_address,
    user_agent,
    is_active
) VALUES 
('251307', NOW() - INTERVAL '2 hours', NOW() - INTERVAL '30 minutes', '192.168.1.100', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', true),
('261401', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '15 minutes', '192.168.1.101', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)', true),
('admin', NOW() - INTERVAL '3 hours', NOW() - INTERVAL '5 minutes', '192.168.1.102', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', true);

-- Add some sample files
INSERT INTO files (
    original_name,
    filename,
    file_path,
    mimetype,
    size_bytes,
    uploaded_by,
    project_id
) VALUES 
('warehouse_before.jpg', 'uuid-123-warehouse_before.jpg', '/uploads/uuid-123-warehouse_before.jpg', 'image/jpeg', 1024000, '241303', 1),
('warehouse_after.jpg', 'uuid-124-warehouse_after.jpg', '/uploads/uuid-124-warehouse_after.jpg', 'image/jpeg', 987000, '241303', 1),
('datacenter_before.jpg', 'uuid-125-datacenter_before.jpg', '/uploads/uuid-125-datacenter_before.jpg', 'image/jpeg', 1234000, '251307', 2),
('datacenter_after.jpg', 'uuid-126-datacenter_after.jpg', '/uploads/uuid-126-datacenter_after.jpg', 'image/jpeg', 1156000, '251307', 2);

COMMENT ON TABLE projects IS 'Contains all Kaizen project data from various form types';
COMMENT ON TABLE sessions IS 'Tracks user login sessions for security and analytics';
COMMENT ON TABLE files IS 'Manages uploaded files associated with projects';